version: '2.1'
services:
  
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    volumes:
      - ./conf/proxy/odoo.conf:/config/nginx/proxy-confs/odoo.subdomain.conf
      - ./conf/proxy/pgadmin.conf:/config/nginx/proxy-confs/pgadmin.subdomain.conf
      - ./conf/proxy/portainer.conf:/config/nginx/proxy-confs/portainer.subdomain.conf
      - ./conf/proxy/duplicati.conf:/config/nginx/proxy-confs/duplicati.subdomain.conf
      - ./conf/htpasswd:/config/nginx/.htpasswd:rw
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
  
  postgresql:
    image: 'bitnami/postgresql:11'
    container_name: postgresql
    hostname: postgresql
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    restart: always
    
  odoo:
    image: 'bitnami/odoo:12'
    container_name: odoo
    hostname: odoo
    volumes:  
      - './odoo_data:/bitnami'
      - './custom-addons:/opt/bitnami/odoo/odoo/addons'
    environment:
      - ODOO_EMAIL=${ODOO_EMAIL}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT_NUMBER=5432
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=465
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PROTOCOL=ssl
    networks:
      cybererp-network:
        aliases:
         - odoo
    depends_on:
      - postgresql
    restart: always  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ODOO_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ODOO_PASSWORD}
    # ports:
    #  - "10080:80"
    depends_on:
      - postgresql
    networks:
      cybererp-network:
        aliases:
         - pgadmin
    restart: always
 
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/portainer:/data
    restart: always
    networks:
      cybererp-network:
        aliases:
         - portainer
  
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ./config/dupicati:/config
      - /opt/backup/duplicati:/backups
      - ./:/source
    ports:
      - 8200:8200
    restart: always
    networks:
      cybererp-network:
        aliases:
         - duplicati
volumes:
  postgresql_data:
  odoo_data: 
networks:
  cybererp-network:
    driver: bridge
